### PR TITLE
Update speakingurl dependency, set to ^1.0.0

### PR DESCRIPTION
**Pull request by vstene**

### CODE REVIEW

**Comment by zappan** [comment]
Thanks. 
Did a 1.0.3 release matching your 1.0.0, and also did a 1.1.0 afterwards to match your 1.1.x since you switched to semver

Cheers

**Comment by pid** [comment]
oh, updated today to v2.0.0 ;-)

**Comment by zappan** [comment]
grrrrrr ;-)

**Comment by pid** [comment]
**grins**

**Comment by vstene** [comment]
It updated to v3.0.0 a few days ago :)

**Pull request merged**
